services:
  fastify-app:
    build: .
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: node_db_test
    ports:
      - '5432:5432'
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
